#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IRSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     RightLight,     sensorCOLORFULL)
#pragma config(Sensor, S4,     LeftLight,      sensorCOLORFULL)
#pragma config(Motor,  motorA,          Block,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Shoulder,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Spinner,       tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int normSpeed = 60;
int trans = 0;

void goForward(const int forward){
	nMotorEncoder(Left) = 0;
	nMotorEncoder(Right) = 0;
	wait1Msec(50);

	motor[Right] = normSpeed * 3;
	motor[Left] = normSpeed * 3;
	while(abs(nMotorEncoder(Left)) < forward && time1(T1) < 5000){
	}
	motor[Right] = 0;
	motor[Left] = 0;

	while(time1(T1) < 23000){
	}
	trans = 1;
}



void toWhiteLine(){
	if(SensorValue(RightLight) != 2 && SensorValue(RightLight) != 5){
		motor[Right] = -normSpeed;
		motor[Left] = -normSpeed;
	}

	if(SensorValue(RightLight) == 2 || SensorValue(RightLight) == 5){
		trans = 2;
	}
}



void goOnPlatform(const int turn, const int forward){
	motor[Right] = 0;
	motor[Left] = 0;

	nMotorEncoder(Left) = 0;
	nMotorEncoder(Right) = 0;
	wait1Msec(50);

	motor[Left] = 0;
	motor[Right] = -100;
	while(abs(nMotorEncoder(Right)) < turn){
	}
	motor[Left] = 0;
	motor[Right] = 0;

	while(time1(T1) < 27000){
	}
	nMotorEncoder(Left) = 0;
	nMotorEncoder(Right) = 0;
	wait1Msec(50);

	motor[Right] = 100;
	motor[Left] = 100;
	while(abs(nMotorEncoder(Right)) < forward){
	}
	motor[Right] = 0;
	motor[Left] = 0;
	wait1Msec(30000);
}



task main(){
	waitForStart();
	ClearTimer(T1);
	nMotorEncoder(Right) = 0;
	nMotorEncoder(Left) = 0;
while(true){
	if(trans == 0) goForward(9000);
	if(trans == 1) toWhiteLine();
	if(trans == 2) goOnPlatform(2500, 5000);
}
}
