#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     IRSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     RightLight,     sensorCOLORFULL)
#pragma config(Motor,  motorA,          Block,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Shoulder,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Spinner,       tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



#include "JoystickDriver.c"

int normSpeed = 50;
int blockSpeed = 50;
int trans = 0;
int delay = 15000;

//BEGINNING LEFT CODE//
void LplaceBlock(const int forward){
	nMotorEncoder(Left) = 0;
	nMotorEncoder(Right) = 0;
	wait1Msec(50);

	motor[Right] = -normSpeed;
	motor[Left] = -normSpeed;
	while(abs(nMotorEncoder(Left)) < forward && SensorValue(IRSeeker) != 5){
	}

	if(SensorValue(IRSeeker) == 5){
		trans = 11;
	}
	else{
		while(abs(nMotorEncoder(Left)) < forward * 4 && SensorValue(IRSeeker) != 4){
		}
		if(SensorValue(IRSeeker) == 4){
			trans = 11;
		}

		if(abs(nMotorEncoder(Left)) >= forward * 4 && SensorValue(IRSeeker) != 4){
			trans = 1;
		}
	}
}

//BEGINNING RIGHT CODE//
void RplaceBlock(const int forward){
	nMotorEncoder(Left) = 0;
	nMotorEncoder(Right) = 0;
	wait1Msec(50);

	motor[Right] = normSpeed;
	motor[Left] = normSpeed;
	while(abs(nMotorEncoder(Left)) < forward && SensorValue(IRSeeker) != 5){
	}

	if(SensorValue(IRSeeker) == 5){
		trans = 11;
	}
	else{
		while(abs(nMotorEncoder(Left)) < forward * 4 && SensorValue(IRSeeker) != 6){
		}
		if(SensorValue(IRSeeker) == 6){
			trans = 11;
		}

		if(abs(nMotorEncoder(Left)) >= forward * 4 && SensorValue(IRSeeker) != 6){
			trans = 9;
		}
	}
}

//RELEASE BLOCK//
void retractStick(const int time){
	trans = 1;
	motor[Block] = blockSpeed;
	motor[Right] = 0;
	motor[Left] = 0;
	wait1Msec(time);

	motor[Block] = -blockSpeed;
	motor[Right] = 0;
	motor[Left] = 0;
	wait1Msec(time);
}

//END LEFT CODE//
void LoutLowGoal(){
   if(SensorValue(RightLight) != 2 && SensorValue(RightLight) != 5){
      motor[Block] = 0;
      motor[Right] = normSpeed;
      motor[Left] = normSpeed;
   }

   if(SensorValue(RightLight) == 2 || SensorValue(RightLight) == 5){
      motor[Block] = 0;
      trans = 2;
   }
}



void Lturn(const int forward, const int turn){
	nMotorEncoder(Right) = 0;
	nMotorEncoder(Left) = 0;

	wait1Msec(50);

	motor[Right] = normSpeed;
	motor[Left] = normSpeed;

	while(abs(nMotorEncoder(Left)) < forward){
		nxtDisplayTextLine(1, "EncL=%d", nMotorEncoder[Right]);
    nxtDisplayTextLine(2, "EncL=%d", nMotorEncoder[Left]);
	}
	motor[Left] = 0;
	motor[Right] = 0;

	nMotorEncoder(Right) = 0;
	nMotorEncoder(Left) = 0;

	wait1Msec(50);

	motor[Right] = 0;
	motor[Left] = normSpeed;

	while(abs(nMotorEncoder(Left)) < turn){
	  nxtDisplayTextLine(1, "EncL=%d", nMotorEncoder[Right]);
    nxtDisplayTextLine(2, "EncL=%d", nMotorEncoder[Left]);
	}

	trans = 3;
}



void Lcenter(){
	if(SensorValue(RightLight) != 2 && SensorValue(RightLight) != 5){
		motor[Right] = normSpeed;
		motor[Left] = normSpeed;
	}

	if(SensorValue(RightLight) == 2 || SensorValue(RightLight) == 5){
		trans = 4;
	}
}



void LgetOnPlatform(const int turn, const int forward){
	nMotorEncoder(Right) = 0;
	nMotorEncoder(Left) = 0;

	wait1Msec(50);

	motor[Right] = -normSpeed;
	motor[Left] = normSpeed;

	while(abs(nMotorEncoder(Right)) < turn){
	}
	motor[Right] = 0;
	motor[Left] = 0;

	nMotorEncoder(Right) = 0;
	nMotorEncoder(Left) = 0;
	wait1Msec(50);

	motor[Right] = normSpeed;
	motor[Left] = normSpeed;

	while(abs(nMotorEncoder(Right)) < forward){
	}

	motor[Right] = 0;
	motor[Left] = 0;
	wait1Msec(30000);
}

//END RIGHT CODE//
void RoutLowGoal(){
   if(SensorValue(RightLight) != 2 && SensorValue(RightLight) != 5){
      motor[Block] = 0;
      motor[Right] = -normSpeed;
      motor[Left] = -normSpeed;
   }

   if(SensorValue(RightLight) == 2 || SensorValue(RightLight) == 5){
      motor[Block] = 0;
      trans = 2;
   }
}



void Rturn(const int forward, const int turn){
	nMotorEncoder(Right) = 0;
	nMotorEncoder(Left) = 0;

	wait1Msec(50);

	motor[Right] = -normSpeed;
	motor[Left] = -normSpeed;

	while(abs(nMotorEncoder(Left)) < forward){
		nxtDisplayTextLine(1, "EncR=%d", nMotorEncoder[Right]);
    nxtDisplayTextLine(2, "EncL=%d", nMotorEncoder[Left]);
	}
	motor[Left] = 0;
	motor[Right] = 0;

	nMotorEncoder(Right) = 0;
	nMotorEncoder(Left) = 0;

	wait1Msec(50);

	motor[Right] = 0;
	motor[Left] = -normSpeed;

	while(abs(nMotorEncoder(Left)) < turn){
	  nxtDisplayTextLine(1, "EncL=%d", nMotorEncoder[Right]);
    nxtDisplayTextLine(2, "EncL=%d", nMotorEncoder[Left]);
	}

	trans = 3;
}



void Rcenter(){
	if(SensorValue(RightLight) != 2 && SensorValue(RightLight) != 5){
		motor[Right] = -normSpeed;
		motor[Left] = -normSpeed;
	}

	if(SensorValue(RightLight) == 2 || SensorValue(RightLight) == 5){
		trans = 4;
	}
}



void RgetOnPlatform(const int turn, const int forward){
	nMotorEncoder(Right) = 0;
	nMotorEncoder(Left) = 0;

	wait1Msec(50);

	motor[Right] = -normSpeed;
	motor[Left] = normSpeed;

	while(abs(nMotorEncoder(Left)) < turn){
	}
	motor[Right] = 0;
	motor[Left] = -normSpeed;

	nMotorEncoder(Right) = 0;
	nMotorEncoder(Left) = 0;
	wait1Msec(50);

	motor[Right] = normSpeed;
	motor[Left] = normSpeed;

	while(abs(nMotorEncoder(Left)) < forward){
	}

	motor[Right] = 0;
	motor[Left] = 0;
	wait1Msec(30000);
}


int side1;
int side2;
int menu = 0;
int selection = 0;
bool DELAY;

//Run command//
void run(){
	//L, L//
	if(side1 == 0 && side2 == 0){
		if(DELAY) wait10Msec(delay);
		nMotorEncoder(Right) = 0;
		nMotorEncoder(Left) = 0;
		wait1Msec(50);
		while(true){
   		if(trans == 0) LplaceBlock(4032);
   		if(trans == 11) retractStick(500);
   		if(trans == 1) LoutLowGoal();
   		if(trans == 2) Lturn(100, 3500);
   		if(trans == 3) Lcenter();
   		if(trans == 4) LgetOnPlatform(1500, 4500);
		}
	}

	//L, R//
	if(side1 == 0 && side2 == 1){
		if(DELAY) wait10Msec(delay);
		nMotorEncoder(Right) = 0;
		nMotorEncoder(Left) = 0;
		wait1Msec(50);
		while(true){
   		if(trans == 0) LplaceBlock(4032);//5040
   		if(trans == 11) retractStick(500);
   		if(trans == 1) RoutLowGoal();
   		if(trans == 2) Rturn(500, 3500);//720, 3120
   		if(trans == 3) Rcenter();
   		if(trans == 4) RgetOnPlatform(1500, 4000);//2160, 5760
		}
	}

	//R, L//
	if(side1 == 1 && side2 == 0){
		if(DELAY) wait10Msec(delay);
		nMotorEncoder(Right) = 0;
		nMotorEncoder(Left) = 0;
		wait1Msec(50);
		while(true){
   		if(trans == 0) RplaceBlock(2880);//3600
   		if(trans == 11) retractStick(500);
   		if(trans == 1) LoutLowGoal();
   		if(trans == 2) Lturn(100, 3500);//720, 3120
   		if(trans == 3) Lcenter();
   		if(trans == 4) LgetOnPlatform(1500, 5000);//2160, 5760
		}
	}

	//R, R//
	if(side1 == 1 && side2 == 1){
		if(DELAY) wait1Msec(delay);
		nMotorEncoder(Right) = 0;
		nMotorEncoder(Left) = 0;
		wait1Msec(50);
		while(true){
   		if(trans == 0) RplaceBlock(2880);//3600
   		if(trans == 11) retractStick(500);
   		if(trans == 1) RoutLowGoal();
   		if(trans == 2) Rturn(500, 1500);//720, 3120
   		if(trans == 3) Rcenter();
   		if(trans == 4) RgetOnPlatform(1500, 4000);//2160, 5760
		}
	}
}


task main()
{
eraseDisplay();
while(menu == 0){
	//Toggle between sides//
	if(nNxtButtonPressed == 1){
		selection++;
		while(nNxtButtonPressed == 1){
		}
	}
	if(nNxtButtonPressed == 2){
		selection--;
		while(nNxtButtonPressed == 2){
		}
	}
	if(selection > 1) selection = 1;
	if(selection < 0) selection = 0;

	//Display option//
	switch(selection){
		case 0:
			nxtDisplayCenteredBigTextLine(3, "%s", "Starting Left");
			break;
		case 1:
			nxtDisplayCenteredBigTextLine(3, "%s", "Starting Right");
			break;
	}

	//Make selection//
	if(nNxtButtonPressed == 3){
		side1 = selection;
		menu++;
		while(nNxtButtonPressed == 3){
		}
	}
}

eraseDisplay();
selection = 0;
while(menu == 1){
	//Toggle between sides//
	if(nNxtButtonPressed == 1){
		selection++;
		while(nNxtButtonPressed == 1){
		}
	}
	if(nNxtButtonPressed == 2){
		selection--;
		while(nNxtButtonPressed == 2){
		}
	}
	if(selection > 1) selection = 1;
	if(selection < 0) selection = 0;

	//Display option//
	switch(selection){
		case 0:
			nxtDisplayCenteredBigTextLine(3, "%s", "Ending Left");
			break;
		case 1:
			nxtDisplayCenteredBigTextLine(3, "%s", "Ending Right");
			break;
	}

	//Make selection//
	if(nNxtButtonPressed == 3){
		side2 = selection;
		menu++;
		while(nNxtButtonPressed == 3){
		}
	}
}

eraseDisplay();
selection = 0;
while(menu == 2){
	//Toggle between sides//
	if(nNxtButtonPressed == 1){
		selection++;
		while(nNxtButtonPressed == 1){
		}
	}
	if(nNxtButtonPressed == 2){
		selection--;
		while(nNxtButtonPressed == 2){
		}
	}
	if(selection > 1) selection = 1;
	if(selection < 0) selection = 0;
	if(selection == 0) DELAY = false;
	if(selection == 1) DELAY = true;

	//Display option//
	switch(selection){
		case 0:
			nxtDisplayCenteredBigTextLine(3, "%s", "Delay: OFF");
			nxtDisplayCenteredBigTextLine(4, "%s", "ORANGE to start!");
			break;
		case 1:
			nxtDisplayCenteredBigTextLine(3, "%s", "DELAY: ON");
			nxtDisplayCenteredBigTextLine(4, "%s", "ORANGE to start!");
			break;
	}

	//Make selection//
	if(nNxtButtonPressed == 3){
		run();
		while(nNxtButtonPressed == 3){
		}
	}
}
}
