#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorMatrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorMatrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#pragma platform(NXT)

#include "JoystickDriver.c"

bool PID;
int speed;
int diameter;
int distance;
int iterations;
int menu = 0;
int selection = 0;
int circumference;
int ticks;

//THIS CODE MEASURES HOW ACCURATE THE ENCODERS CAN BE//
task main()
{
eraseDisplay();

//Set wheel diameter//
selection = 3;
while(menu == 0){
	if(nNxtButtonPressed == 1){
		selection++;
		while(nNxtButtonPressed == 1){
		}
	}
	if(nNxtButtonPressed == 2){
		selection--;
		while(nNxtButtonPressed == 2){
		}
	}
	if(selection < 3) selection = 3;
	if(selection > 5) selection = 5;

	nxtDisplayCenteredBigTextLine(3, "%s, %i", "Diameter = ", selection);

	if(nNxtButtonPressed == 3){
		diameter = selection;
		menu++;
		while(nNxtButtonPressed == 3){
		}
	}
}

//Set speed//
selection = 75;
while(menu == 1){
	if(nNxtButtonPressed == 1){
		selection += 25;
		while(nNxtButtonPressed == 1){
		}
	}
	if(nNxtButtonPressed == 2){
		selection -= 25;
		while(nNxtButtonPressed == 2){
		}
	}
	if(selection < 25) selection = 25;
	if(selection > 100) selection = 100;

	nxtDisplayCenteredBigTextLine(3, "%s, %i", "Speed = ", selection);

	if(nNxtButtonPressed == 3){
		speed = selection;
		menu++;
		while(nNxtButtonPressed == 3){
		}
	}
}

//Set distance//
selection = 1;
while(menu == 2){
	if(nNxtButtonPressed == 1){
		selection++;
		while(nNxtButtonPressed == 1){
		}
	}
	if(nNxtButtonPressed == 2){
		selection--;
		while(nNxtButtonPressed == 2){
		}
	}
	if(selection < 1) selection = 1;

	nxtDisplayCenteredBigTextLine(3, "%s, %i, %s", "Distance = ", selection, " feet");

	if(nNxtButtonPressed == 3){
		distance = selection;
		menu++;
		while(nNxtButtonPressed == 3){
		}
	}
}

//How many times//
selection = 1;
while(menu == 3){
	if(nNxtButtonPressed == 1){
		selection++;
		while(nNxtButtonPressed == 1){
		}
	}
	if(nNxtButtonPressed == 2){
		selection--;
		while(nNxtButtonPressed == 2){
		}
	}
	if(selection < 1) selection = 1;

	nxtDisplayCenteredBigTextLine(3, "%s, %i", "Number of iteration = ", selection);

	if(nNxtButtonPressed == 3){
		iterations = selection;
		menu++;
		while(nNxtButtonPressed == 3){
		}
	}
}

//PID?//
PID = false;
while(menu == 4){
	if(nNxtButtonPressed == 1){
		PID = !PID;
		while(nNxtButtonPressed == 1){
		}
	}
	if(nNxtButtonPressed == 2){
		PID = !PID;
		while(nNxtButtonPressed == 2){
		}
	}

	if(PID){
		nxtDisplayCenteredBigTextLine(3, "%s", "PID: YES");
	}
	else{
		nxtDisplayCenteredBigTextLine(3, "%s", "PID: NO");
	}

	if(nNxtButtonPressed == 3){
		menu++;
		while(nNxtButtonPressed == 3){
		}
	}
}

//Run//
while(menu == 5){
	circumference = PI * diameter;
	ticks = 1440 * distance / circumference;
	nMotorEncoder(Right) = 0;
	nMotorEncoder(Left) = 0;
	wait1Msec(50);

	for(int i = 1; i < iterations; i++){
		while(nNxtButtonPressed != 3){
		}
		motor[Right] = speed;
		motor[Left] = speed;
		while(abs(nMotorEncoder(Right)) < ticks && abs(nMotorEncoder(Left)) < ticks){
		}
		motor[Right] = 0;
		motor[Left] = 0;
	}
}
}
