#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#pragma platform(NXT)

#include "JoystickDriver.c"

int speed = 75;
int autonomous = 300;
int teleop = 1200;
int time;
int Volts;
//times in 0.1secs//

//This program runs a battery like a match, to see how low the voltage can drop in 2.5 min//
task main()
{
waitForStart();
ClearTimer(T1);
AddToDatalog(speed, speed);
AddToDatalog(Volts, nAvgBatteryLevel);

motor[Right] = speed;
motor[Left] = -speed;
while(time100(T1) <= autonomous){
	//Every 10 seconds//
	if((time100(T1) % 100) == 0){
		AddToDatalog(time, time100(T1));
		AddToDatalog(Volts, nAvgBatteryLevel);
	}
}
motor[Right] = 0;
motor[Left] = 0;
wait1Msec(10000);
//Pause like actual match//
ClearTimer(T1);

motor[Right] = speed;
motor[Left] = speed;
while(time100(T1) <= teleop){
	//Every 10 seconds//
	if((time100(T1) % 100) == 0){
		AddToDatalog(time, time100(T1));
		AddToDatalog(Volts, nAvgBatteryLevel);
	}
}
SaveNxtDatalog();
}
