#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     IRSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     RightLight,     sensorCOLORFULL)
#pragma config(Motor,  motorA,          Block,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Spinner,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Arm,           tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int motorVal = 1;
int motorDir = 1;
int menu = 0;
/*Menus:
0 - motor selection
1 - direction selection
2 - motor movement
*/

task main()
{
eraseDisplay();
while(true){
//Read arrow toggles//
while(menu == 0){
	if(nNxtButtonPressed == 1){
		motorVal++;
		while(nNxtButtonPressed == 1){
		}
	}
	if(nNxtButtonPressed == 2){
		motorVal--;
		while(nNxtButtonPressed == 2){
		}
	}
	if(motorVal <= 0){
		motorVal = 1;
	}
	if(motorVal >= 6){
		motorVal = 5;
	}

	switch(motorVal){
		case 1:
			nxtDisplayCenteredBigTextLine(3, "%s", "Motor: Block");
			break;
		case 2:
			nxtDisplayCenteredBigTextLine(3, "%s", "Motor: Left Drive");
			break;
		case 3:
			nxtDisplayCenteredBigTextLine(3, "%s", "Motor: Right Drive");
			break;
		case 4:
			nxtDisplayCenteredBigTextLine(3, "%s", "Motor: Spinner");
			break;
		case 5:
			nxtDisplayCenteredBigTextLine(3, "%s", "Motor: Arm");
			break;
		default:
			nxtDisplayCenteredBigTextLine(3, "%s", "Error!");
			break;
	}

	if(nNxtButtonPressed == 3){
		menu = 1;
		while(nNxtButtonPressed == 3){
		}
	}
}

eraseDisplay();

while(menu == 1){
	if(nNxtButtonPressed == 1){
		motorDir = 1;
		while(nNxtButtonPressed == 1){
		}
	}
	if(nNxtButtonPressed == 2){
		motorDir = -1;
		while(nNxtButtonPressed == 2){
		}
	}

	nxtDisplayBigTextLine(3, "%s%i", "Motor Direction: ", motorDir * 50);

	if(nNxtButtonPressed == 3){
		menu = 2;
		while(nNxtButtonPressed == 3){
		}
	}
}

eraseDisplay();

while(menu == 3){
	nxtDisplayCenteredBigTextLine(3, "%s", "Press orange button to move motor...");
	while(nNxtButtonPressed == 3){
	switch(motorVal){
		case 1:
				motor[Block] = 50 * motorDir;
		case 2:
				motor[Left] = 50 * motorDir;
		case 3:
				motor[Right] = 50 * motorDir;
		case 4:
				motor[Spinner] = 50 * motorDir;
		case 5:
				motor[Arm] = 50 * motorDir;
		default:
			nxtDisplayCenteredBigTextLine(3, "%s", "Error!");
	}
	motor[Block] = 0;
	motor[Left] = 0;
	motor[Right] = 0;
	motor[Spinner] = 0;
	motor[Arm] = 0;
	}
}
}
}
